language: java
jdk:
- oraclejdk8
deploy:
  provider: releases
  file: target/beancp-0.1.jar
  on:
    repo: erchu/bean-cp
env:
  global:
    secure: DJ9xHEbxAPOeGoGova0NEll9ziYZI8DLneMl6/lEmhLxQ3NdumBvL9C5l3TIcrpPX4oD9cK4hhpWfxOIC2WvNS1GEXeWgg1aOzKOQryCLH9y8bXfvSB/zLOQjk3plYJz84k3XxE/voWaRN7KzHKw9A97/s0/iS5eBEfHR4xpZdw=
